version: "3"

services:
  mongoDB:
    image: mongo:3.6.2
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
    volumes:
      - /data/dc1_db1:/data/db
    ports:
      - "27017:27017"
    networks:
      - private_net

  Jenkins:
    image: jenkins-docker
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
    volumes:
      - /var/jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8080:8080"
      - "50000:50000"
    networks:
      - private_net

  BusyBox:
    image: busybox
    command: "top"
    deploy:
      replicas: 1
    networks:
      - private_net

  Visualizer:
    image: dockersamples/visualizer:stable
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
    ports:
      - "9000:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - private_net
    
networks:
  private_net:

