---
# Swarm Builder Ansible Playbook

- name: Install Docker Prereqs
  hosts: swarm-managers:swarm-nodes
  become: yes
  gather_facts: yes
  tasks:
    - package:
        name: "{{item}}"
        state: latest
      with_items:
        - apt-transport-https
        - ca-certificates
        - curl
        - software-properties-common
    - apt_key:
        url: "https://download.docker.com/linux/ubuntu/gpg"
        state: present
    - apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable"
        state: present
 

- name: Install Docker
  hosts: swarm-managers:swarm-nodes
  become: yes
  gather_facts: yes
  tasks:
    - package:
        name: "docker-ce"
        state: latest
    - user: 
        name: "{{ ansible_user }}"
        groups: docker
        append: yes


- name: Initialize Swarm Master
  hosts: swarm-manager-01
  gather_facts: yes
  tasks:
    - debug: var=ansible_default_ipv4.address
    - command: "docker swarm init --advertise-addr {{ansible_default_ipv4.address}}"
    - command: "docker swarm join-token -q worker"
      register: swarm_token
    - set_fact: swarmtoken="{{swarm_token.stdout}}"


- name: Join Swarm Nodes
  hosts: swarm-nodes
  gather_facts: yes
  tasks:
  - command: > 
        docker swarm join
        --token {{hostvars[groups['swarm-managers'][0]].swarmtoken}}
        --advertise-addr {{ansible_default_ipv4.address}}
        {{hostvars[groups['swarm-managers'][0]].ansible_default_ipv4.address}}:2377


- name: Create DB Directory
  hosts: swarm-manager-01
  become: yes
  tasks:
    - file:
        path: /data/dc1_db1
        state: directory


- name: Clone DC1 Repository
  hosts: swarm-manager-01
  tasks:
  - git: >
      repo=https://github.com/hmashaw-tech/dc1.git
      dest=/home/ubuntu/dc1


# Add or modify memlock, both soft and hard, limit for all users with a comment.
- pam_limits:
    domain: *
    limit_type: '-'
    limit_item: memlock
    value: unlimited
    comment: unlimited memory lock for *

