- name: Leave Swarm
  hosts: swarm-managers:swarm-nodes
  gather_facts: yes
  tasks:
    - command: "docker swarm leave --force"

- name: Remove cloned DC1 directory
  hosts: swarm-managers
  gather_facts: yes
  tasks:
  file:
    path: /data/dc1_db1
    state: absent

